#!/bin/sh
set -e
# Automatically added by dh_installinit/13.7.1
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d seatd remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.7.1
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.7.1
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'seatd.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'seatd.service' >/dev/null || true
		deb-systemd-helper unmask 'seatd.service' >/dev/null || true
	fi
fi
# End automatically added section
